# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CYBERJUNKIE
email: cyb3rjunki3@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bem vindo ao lixão cyberpunk brasileiro!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cyberjunkie.cf" # the base hostname & protocol for your site
twitter_username: cybertwitter
github_username:  cybergithub

# Build settings
markdown: kramdown
